<?xml version="1.0" encoding="utf-8"?>
<Database Name="Epm" Class="EpmDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\Epm.mdf;Integrated Security=True;User Instance=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="EpmConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Project" Member="Projects">
    <Type Name="Project">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="[desc]" Member="desc" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="start" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[end]" Member="end" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="status" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
    </Type>
  </Table>
</Database>